INHERIT: docs_template/mkdocs.yml

docs_dir: 'docs'

repo_name: Centurion UI
repo_url: https://github.com/nofusscomputing/centurion_ui
edit_uri: '/edit/development/docs/'
theme: 
  icon:
    repo: fontawesome/brands/github


nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Centurion ERP:

    - projects/centurion_erp/index.md

  - Centurion User Interface:

    - API:

      - projects/centurion_user_interface/api/index.md

    - User Interface:

      - Components:

        - projects/centurion_user_interface/user/components/comment.md

      - Fields:

        - projects/centurion_user_interface/user/fields/markdown.md

      - projects/centurion_user_interface/user/index.md

      - projects/centurion_user_interface/user/notifications.md

    - projects/centurion_user_interface/index.md

    - projects/centurion_user_interface/development.md

    - projects/centurion_user_interface/describing.md

    - projects/centurion_user_interface/setup.md

- Operations: 

  - operations/index.md

- Contact Us: contact.md

